"""Added description field for Figure model
Revision ID: 26955b5df6a1
Revises: cb58512b1c91
Create Date: 2022-05-14 12:46:18.841480
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '26955b5df6a1'
down_revision = 'cb58512b1c91'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multilinefigure', sa.Column('description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multilinefigure', 'description')
    # ### end Alembic commands ###