"""Fixes
Revision ID: 3fb4cb05ad22
Revises: d6d7e9ae27b7
Create Date: 2022-05-01 12:00:41.090042
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '3fb4cb05ad22'
down_revision = 'd6d7e9ae27b7'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_id', table_name='token')
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=True)
    op.drop_index('ix_user_uuid', table_name='user')
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.create_index('ix_user_uuid', 'user', ['uuid'], unique=False)
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.create_index('ix_token_id', 'token', ['id'], unique=False)
    # ### end Alembic commands ###