"""added token model and fix user model
Revision ID: 4fad59946e6d
Revises: df64f4aa9aa6
Create Date: 2022-04-06 17:55:19.557863
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "4fad59946e6d"
down_revision = "df64f4aa9aa6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    # ### end Alembic commands ###
