"""Added Multiline figure
Revision ID: cb58512b1c91
Revises: 5323e78a61de
Create Date: 2022-05-08 17:24:36.034804
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic
revision = 'cb58512b1c91'
down_revision = '5323e78a61de'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multilinefigure',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('figure_type', sa.Enum('map', name='figuretype'), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('x_axis', sa.PickleType(), nullable=True),
    sa.Column('datasets', sa.JSON(), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multilinefigure_id'), 'multilinefigure', ['id'], unique=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_multilinefigure_id'), table_name='multilinefigure')
    op.drop_table('multilinefigure')
    # ### end Alembic commands ###