"""add password
Revision ID: df64f4aa9aa6
Revises: 016c23f38538
Create Date: 2022-04-03 17:18:10.664131
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "df64f4aa9aa6"
down_revision = "016c23f38538"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=256), nullable=False))
    op.add_column("user", sa.Column("salt", sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "salt")
    op.drop_column("user", "password")
    # ### end Alembic commands ###
